DELETE FROM TRAINER;
TRUNCATE TABLE TRAINER;
ALTER SEQUENCE TRAINER.ID RESTART WITH 1;
INSERT INTO TRAINER (AGE, EMAIL, FIRST_NAME) VALUES ('20', 'amccall@qa.com', 'Andrew');
INSERT INTO TRAINER (AGE, EMAIL, FIRST_NAME) VALUES ('20', 'amccall@qa.com', 'Andrew');