DELETE FROM TRAINER;
INSERT INTO TRAINER (ID, AGE, EMAIL, FIRST_NAME) VALUES ('1' , '20', 'amccall@qa.com', 'Andrew');
INSERT INTO TRAINER (ID, AGE, EMAIL, FIRST_NAME) VALUES ('2' , '20', 'amccall@qa.com', 'Andrew');
